version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - pdf

python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
